// Mock data used when backend is not running
import type { Job } from "./api";

export const CATEGORIES = [
  "Design", "Sales", "Marketing", "Finance",
  "Technology", "Engineering", "Business", "Human Resource",
] as const;

export const JOB_TYPES = ["Full Time", "Part Time", "Contract", "Internship"] as const;

export const mockJobs: Job[] = [
  {
    _id: "1",
    title: "Email Marketing",
    company: "Revolut",
    location: "Madrid, Spain",
    category: "Marketing",
    type: "Full Time",
    description: "Revolut is looking for an Email Marketing specialist to help team manage campaigns, analytics and customer outreach. You will work closely with the design and product teams to drive user engagement through effective email strategies.",
    tags: ["Marketing", "Design"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "2",
    title: "Brand Designer",
    company: "Dropbox",
    location: "San Fransisco, US",
    category: "Design",
    type: "Full Time",
    description: "Dropbox is looking for a Brand Designer to help the team create compelling visual narratives across all channels. You will shape and evolve the brand identity, ensuring consistency and excellence in every touchpoint.",
    tags: ["Design", "Business"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "3",
    title: "Email Marketing",
    company: "Pitch",
    location: "Berlin, Germany",
    category: "Marketing",
    type: "Full Time",
    description: "Pitch is looking for a Customer Manager to join marketing team. You'll be responsible for developing email campaigns, analyzing performance metrics, and optimizing conversion funnels to drive growth.",
    tags: ["Marketing"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "4",
    title: "Visual Designer",
    company: "Blinklist",
    location: "Granada, Spain",
    category: "Design",
    type: "Full Time",
    description: "Blinklist is looking for a Visual Designer to help team design beautiful and intuitive user interfaces. You will collaborate with product and engineering teams to create delightful experiences for our users.",
    tags: ["Design"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "5",
    title: "Product Designer",
    company: "ClassPass",
    location: "Manchester, UK",
    category: "Design",
    type: "Full Time",
    description: "ClassPass is looking for a Product Designer to help us create world-class fitness experiences. You'll lead design for key product features, conduct user research, and iterate on solutions that delight millions of users.",
    tags: ["Marketing", "Design"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "6",
    title: "Lead Designer",
    company: "Canva",
    location: "Ontario, Canada",
    category: "Design",
    type: "Full Time",
    description: "Canva is looking for a Lead Engineer to help develop next-generation design tools. You'll mentor a team of designers, set design direction, and ensure our product maintains the highest standards of visual excellence.",
    tags: ["Design", "Business"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "7",
    title: "Brand Strategist",
    company: "GoDaddy",
    location: "Marseille, France",
    category: "Marketing",
    type: "Full Time",
    description: "GoDaddy is looking for a Brand Strategist to join the team. You'll develop brand positioning, messaging frameworks, and go-to-market strategies that resonate with small business owners worldwide.",
    tags: ["Marketing"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "8",
    title: "Data Analyst",
    company: "Twitter",
    location: "San Diego, US",
    category: "Technology",
    type: "Full Time",
    description: "Twitter is looking for a Data Analyst to help team design data-driven strategies. You'll analyze user behavior, build dashboards, and provide actionable insights that inform product and business decisions.",
    tags: ["Technology"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "9",
    title: "Social Media Assistant",
    company: "Nomad",
    location: "Paris, France",
    category: "Marketing",
    type: "Full Time",
    description: "Nomad is looking for a Social Media Assistant to manage content across platforms. You'll create engaging posts, track analytics, and help grow our community of digital nomads and remote workers.",
    tags: ["Marketing", "Design"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "10",
    title: "Interactive Developer",
    company: "Terraform",
    location: "Hamburg, Germany",
    category: "Engineering",
    type: "Full Time",
    description: "Terraform is looking for an Interactive Developer to build immersive web experiences. You'll push the boundaries of web technology to create engaging, performant applications using modern frameworks.",
    tags: ["Engineering", "Design"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "11",
    title: "HR Manager",
    company: "Packer",
    location: "Lucern, Switzerland",
    category: "Human Resource",
    type: "Full Time",
    description: "Packer is looking for an HR Manager to oversee talent acquisition, employee relations, and organizational development. You'll build a world-class team culture and drive people-first initiatives.",
    tags: ["Human Resource", "Business"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "12",
    title: "Frontend Developer",
    company: "Udacity",
    location: "Hamburg, Germany",
    category: "Engineering",
    type: "Full Time",
    description: "Udacity is looking for a Frontend Developer to help build the next generation of online learning experiences. You'll work with React, TypeScript and modern web technologies.",
    tags: ["Engineering", "Technology"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
